### ISSUE TITLE
pdf-xmi-pipeline tries to overwrite typesystem.xml

### ISSUE THREAD

**Issue by neumannm** [openminted/uc-tdm-socialsciences#35]
An error is printed to console when running the PdfToXmi pipeline without overwrite flag. 

 `... Caused by: java.io.IOException: Target file [.\output\converted\de\typesystem.xml] already exists and overwriting not enabled.`

Although this exception is totally legit for normal output files in case they already exist and overwrite flag is not set, this should not happen for the typesystem.xml

It seems like the program wants to create a separate typesystem.xml for each converted file. This should be changed in the future.

**Comment by neumannm** [comment]
I'm not even sure if this is a problem of our code or of XmiWriter. We give the flag `overwrite` to XmiWriter. But if `overwrite=false`, the writer will produce this error when it tries to write the typesystem.xml again for the second processed resource.

**Comment by reckart** [comment]
xmiwriter had an internal check to only write the type system for the first document in a pipeline. Are you writing with multiple pipelines to the same folder?

**Comment by neumannm** [comment]
I think it's only one pipeline. But if you could find time to check yourself... See  https://github.com/openminted/uc-tdm-socialsciences/blob/master/ss-io-pdfx-xml/src/main/java/eu/openminted/uc/socialsciences/io/pdfx/PdfxXmlToXmiConverter.java#L171

**Comment by maxxkia** [comment]
@reckart I checked and I confirm that it fails because of overwrite error (wrong error) although it is in a single pipeline run.

**Comment by maxxkia** [comment]
Here's the error message

```
Jan 23, 2017 6:19:50 PM org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl processAndOutputNewCASes(273)
SEVERE: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.tudarmstadt.ukp.dkpro.core.io.xmi.XmiWriter.process(XmiWriter.java:93)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:397)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:314)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:150)
	at eu.openminted.uc.socialsciences.io.pdfx.PdfxXmlToXmiConverter.convertToXmi(PdfxXmlToXmiConverter.java:167)
	at eu.openminted.uc.socialsciences.io.pdfx.PdfxXmlToXmiConverter.run(PdfxXmlToXmiConverter.java:114)
	at eu.openminted.uc.socialsciences.io.pdfx.PdfxXmlToXmiConverter.main(PdfxXmlToXmiConverter.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.IOException: Target file [ss-io-pdfx-xml/target/temp/typesystem.xml] already exists and overwriting not enabled.
	at de.tudarmstadt.ukp.dkpro.core.api.io.JCasFileWriter_ImplBase.getOutputStream(JCasFileWriter_ImplBase.java:216)
	at de.tudarmstadt.ukp.dkpro.core.io.xmi.XmiWriter.writeTypeSystem(XmiWriter.java:108)
	at de.tudarmstadt.ukp.dkpro.core.io.xmi.XmiWriter.process(XmiWriter.java:88)
	... 17 more

Exception in thread "main" org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.tudarmstadt.ukp.dkpro.core.io.xmi.XmiWriter.process(XmiWriter.java:93)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:397)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:314)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:150)
	at eu.openminted.uc.socialsciences.io.pdfx.PdfxXmlToXmiConverter.convertToXmi(PdfxXmlToXmiConverter.java:167)
	at eu.openminted.uc.socialsciences.io.pdfx.PdfxXmlToXmiConverter.run(PdfxXmlToXmiConverter.java:114)
	at eu.openminted.uc.socialsciences.io.pdfx.PdfxXmlToXmiConverter.main(PdfxXmlToXmiConverter.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.IOException: Target file [ss-io-pdfx-xml/target/temp/typesystem.xml] already exists and overwriting not enabled.
	at de.tudarmstadt.ukp.dkpro.core.api.io.JCasFileWriter_ImplBase.getOutputStream(JCasFileWriter_ImplBase.java:216)
	at de.tudarmstadt.ukp.dkpro.core.io.xmi.XmiWriter.writeTypeSystem(XmiWriter.java:108)
	at de.tudarmstadt.ukp.dkpro.core.io.xmi.XmiWriter.process(XmiWriter.java:88)
	... 17 more
```

Apparently this happens since XmiWriter calls getOutputStream (line 108) although it's already written when the previous document was processed.

**Comment by maxxkia** [comment]
You can reproduce this problem by running PdfxXmlToXmiConverter using these arguments:

-i src/test/resources/ -home src/main/resources/ -o target/temp -lang en

**Comment by reckart** [comment]
Check the xmiwriter code and you should see the if clause that should avoid writing the TS twice. Can you debug it ?

**Comment by maxxkia** [comment]
Oh, I found it.
`typeSystemWritten` is set to true but `typeSystemFile` is null. It's never initialized in the code.

**Comment by maxxkia** [comment]
Ok, `typeSystemFile` is a parameter. So I think the logic
```
if (!typeSystemWritten || typeSystemFile == null)
```
should be changed to
```
if (!typeSystemWritten && typeSystemFile == null)
```

**Comment by maxxkia** [comment]
fixed it in dkpro-core.
